### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by mohala562**
I fixed some bugs and am planning to add some more modules in the future as we are using a ZKteco based device at work.

Cheers

### CODE REVIEW

**Comment by mohala562** [comment]
Please respond to my pull request - its not fair to others to leave that code buggy if a solution is available - the original source has also already been merged with my fixes.

**Comment by anassahmed** [comment]
We are really sorry. We need to check the code first on our attendance machines and read it thoroughly. Maybe this weekend, we'll upgrade the PyPy packages too.

Thanks for your contribution. It's really appreciated.

**Comment by amrnegm** [comment]
@defc0n1 I tried your code against the machines we have. They didn't work. The machines we have don't support SOAP service you are trying to connect to. We couldn't verify it is working or not.
Could you send us the machine model you developed your solution on it?

**Comment by EbtsamSaad** [comment]
@amrnegm @AlSayedGamal  @anassahmed 
is this library worked with all attendance machine type ( TFT , IFACE , BLACK AND WHITE )

**Comment by amrnegm** [comment]
It should be supporting TFT, but it has some parsing problems, though.

**Comment by BMmoh** [comment]
thanks for library but this library for Python 2.7 so i can't run it in  python 3 if someone help me please

**Pull request merged**
